#cloud-config
hostname: rancherosvm
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDHzc4sKS9cCvOFkJNG/JxBYVoFLJVBny3Zqmo0ubmGK0PCoakwwARA9hv6/y2nL67jiWMdderf2bp4FiU0CLEIsDyZfOOUMlUZbCo6Bipv6O75KGYxtUPh8JOdyqONRLfi0qeS6hEHsdVy3dpqyFWlUqcBLsq9boGwNmyirhyfIgkCEF2ljNYLOfGcSW/0QdUFUmdSWjdaBHcwMoDhp2bGtO9NrIvZ5OOVWCloiHRcMAzPK1JXei7j+MEHXsIZZzdgA/pcje6hGedqOQ0GT3/jc4iVCQje2/tgYtNgm40pzDNaErZ3JpflYhsf1unLQECM3ulxsSaB65KYUQKsZmLk/b1KGZLWCcOEbA+ov4adaU3+pziBZMSKUBu7P79kABBzelYiIdyfGtwedui/BcigcCo0srIuSvHJa2vz8cSXQkq4ysBoWIu7ZU/9eVdn3TdJ7OYqxDV1GFjdrlEi7W2TIanMnvx9QRH8PDH+co/nYML8PC6vh8LBPnQjtbM+hTM= Katrina@katrinas-MacBook-Pro.local
  
runcmd:
  - echo "true" > /home/rancher/provisioned
  
write_files:
  - path: /etc/docker/certs.d/private-registry.internal/cert.crt
    permissions: "0644"
    owner: root
    content: |
      -----BEGIN CERTIFICATE-----
      MIICKzCCAdWgAwIBAgIJAIMGUj8Nj8nNMA0GCSqGSIb3DQEBBQUAMEUxCzAJBgNV
      BAYTAkRFMRMwEQYDVQQIEwpTb21lLVN0YXRlMSEwHwYDVQQKExhJbnRlcm5ldCBX
      aWRnaXRzIFB0eSBMdGQwHhcNMTgxMTI4MTg0OTUwWhcNMjAxMTI3MTg0OTUwWjBF
      MQswCQYDVQQGEwJERTETMBEGA1UECBMKU29tZS1TdGF0ZTEhMB8GA1UEChMYSW50
      ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALL7
      789lpQLardPKcuFGAWE9+NwEqjogccYCNzTHVEeuaTfkzUEQkwfc2CdpLDjimeTd
      mZlBlAC89PDRpQlLd7ECAwEAAaOBpzCBpDAdBgNVHQ4EFgQUhR930x7NxpBnUucH
      MXNbJgwLno8wdQYDVR0jBG4wbIAUhR930x7NxpBnUucHMXNbJgwLno+hSaRHMEUx
      CzAJBgNVBAYTAkRFMRMwEQYDVQQIEwpTb21lLVN0YXRlMSEwHwYDVQQKExhJbnRl
      cm5ldCBXaWRnaXRzIFB0eSBMdGSCCQCDBlI/DY/JzTAMBgNVHRMEBTADAQH/MA0G
      CSqGSIb3DQEBBQUAA0EAoKHUppdUCyrMZLRJsrm/pnLq5WqFysT39976/vQvOiP6
      +23OO/Qf3vJZo59MEE2B3hJl0UfkNXobQyDun9gySw==
      -----END CERTIFICATE-----

rancher:
  console: ubuntu
  network:
    dns:
      nameservers:
        - 1.1.1.1
        - 1.0.0.1
      override: true # Override DHCP assigned nameservers
    interfaces:
#       eth0:
#         dhcp: true
      eth0:
        dhcp: false
        address: 172.68.0.69/24
        gateway: 172.68.0.1
#         mtu: 1500
#         vlans: 100

  services:
#     rancher-agent:
#       image: rancher/agent   # default tag v0.8.2
#       command: http://<rancher-server-ip>:8080/v1/projects/1a5/scripts/<registrationToken>
#       privileged: true
#       volumes:
#         - /var/run/docker.sock:/var/run/docker.sock
        
  docker:
    registry_mirror: "https://mirror.gcr.io"
    extra_args: ['--bip=172.20.0.1/16','--fixed-cidr=172.20.0.0/17']
    engine: docker-17.03.2-ce
    
  system_docker:
    # Configure registry mirror (pull through cache) for System Docker
    # Ref: https://docs.docker.com/registry/recipes/mirror/
    registry_mirror: "http://10.10.10.23:5555"

  sysctl:
    vm.max_map_count: 262144
    
  registry_auths:
    https://index.docker.io/v1/:
      username: chrispnugget88
      password: Qw^n27szGLlhrJX%VO3zmz*R
